#!/bin/bash
# Run the swift test suite with TINY_AUDIO_E2E=1, which exercises tests that
# actually load the model bundle and run MLX inference (PrefixCacheTests,
# MicrophoneTranscriberTests). First run downloads ~460 MB of model weights.
#
# `swift build` and `swift test` do not produce `mlx.metallib` — only Xcode's
# Metal toolchain does. Without it, every MLX kernel call traps. To bridge
# this we:
#   1. Run `xcodebuild build` against the SwiftPM-autogenerated `TinyAudio`
#      scheme into a known DerivedData path under `.build/`. xcodebuild
#      compiles the Cmlx target's `.metal` sources into `default.metallib`,
#      placed inside `mlx-swift_Cmlx.bundle`.
#   2. Build the SwiftPM test bundle (`swift build --build-tests`) so
#      `.build/...TinyAudioPackageTests.xctest` exists.
#   3. Copy the metallib next to the test executable as `mlx.metallib`,
#      matching MLX's first colocated-library search path
#      (mlx-swift/Source/Cmlx/mlx/mlx/backend/metal/device.cpp).
#   4. Run `swift test` with TINY_AUDIO_E2E=1.
#
# Tolerates the known MLX `Failed to load the default metallib` teardown
# crash that fires after all tests pass (same heuristic as run-swift-test.sh).

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SWIFT_DIR="$REPO_ROOT/swift"
SCHEME="TinyAudio"
ARCH="$(uname -m)"
case "$ARCH" in
  arm64) DEST_ARCH="arm64" ;;
  x86_64) DEST_ARCH="x86_64" ;;
  *) echo "error: unsupported arch $ARCH" >&2; exit 1 ;;
esac

cd "$SWIFT_DIR"

DERIVED_DATA="$SWIFT_DIR/.build/xcode-derived"
METALLIB_SRC="$DERIVED_DATA/Build/Products/Debug/mlx-swift_Cmlx.bundle/Contents/Resources/default.metallib"

if command -v xcbeautify >/dev/null 2>&1; then
  PRETTY=(xcbeautify --quiet)
else
  PRETTY=(cat)
fi

echo "==> xcodebuild build (produces mlx.metallib via Xcode's Metal toolchain)"
set -o pipefail
xcodebuild build \
  -workspace .swiftpm/xcode/package.xcworkspace \
  -scheme "$SCHEME" \
  -destination "platform=macOS,arch=$DEST_ARCH" \
  -configuration Debug \
  -derivedDataPath "$DERIVED_DATA" \
  -quiet \
  | "${PRETTY[@]}"
set +o pipefail

if [ ! -f "$METALLIB_SRC" ]; then
  echo "error: mlx.metallib not found at $METALLIB_SRC" >&2
  echo "       (xcodebuild build should have produced it — check the build log)" >&2
  exit 1
fi

echo "==> swift build --build-tests (produces the SwiftPM xctest bundle)"
swift build --build-tests

XCTEST_MACOS_DIR="$SWIFT_DIR/.build/$DEST_ARCH-apple-macosx/debug/TinyAudioPackageTests.xctest/Contents/MacOS"
if [ ! -d "$XCTEST_MACOS_DIR" ]; then
  echo "error: test bundle not found at $XCTEST_MACOS_DIR" >&2
  exit 1
fi

echo "==> Copying mlx.metallib next to test binary"
cp "$METALLIB_SRC" "$XCTEST_MACOS_DIR/mlx.metallib"

echo "==> swift test (TINY_AUDIO_E2E=1)"
LOG="$(mktemp)"
trap 'rm -f "$LOG"' EXIT

TINY_AUDIO_E2E=1 swift test 2>&1 | tee "$LOG"
EXIT=${PIPESTATUS[0]}

if [ "$EXIT" -eq 0 ]; then
  exit 0
fi

# Same heuristic as run-swift-test.sh: MLX prints a teardown error after
# all tests pass when the metallib gets unloaded. Treat as success only if
# no test-failure markers are present.
if grep -q "Failed to load the default metallib" "$LOG" \
   && ! grep -qE "(✘|Test run had| failed after )" "$LOG"; then
  echo "note: ignoring known MLX metallib teardown crash (all tests passed)"
  exit 0
fi

exit "$EXIT"
